## [문제] 타이타닉 데이터(./titanic/train.csv') 이용하여 아래의 질문에 답하는 코드를 작성하시오.

In [1]:
import pandas as pd

titanic = pd.read_csv('./titanic/train.csv')
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#### <처리조건> 각 문제의 결과를 데이터 프레임에 저장하도록 한다.

#### (1) 결측값 처리: 처리한 결과를 기존 데이터 프레임에 재저장
- Age : 평균값으로 결측값 처리
- Embarked : 최빈값으로 결측값 처리

##### Age

In [2]:
x = titanic.Age
x

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [3]:
data01 = x.mean(axis=0)
data01

29.69911764705882

In [4]:
df01 = titanic

##### Embarked

#### (2) 레이블 인코딩: 기존 데이터 프레임을 새로dns 데이터 프레임으로 저장한 다음 처리한 결과를 기존 데이터 컬럼은 삭제하고 새로운 데이터 프레임에 재저장
- Sex
- Embarked

##### Sex

In [5]:
from sklearn.preprocessing import LabelEncoder

le01 = LabelEncoder()
titanic01 = titanic
titanic01['Sex'] = le01.fit_transform(titanic01['Sex'])
titanic01.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C

##### Embarked

In [6]:
from sklearn.preprocessing import LabelEncoder

le02 = LabelEncoder()
titanic02 = titanic
titanic02['Embarked'] = le02.fit_transform(titanic02['Embarked'])
titanic02.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,0

#### (3) 원핫인코딩: 기존 데이터 프레임을 새로은 데이터 프레임으로 저장한 다음 처리한 결과를 기존 데이터 컬럼은 삭제하고 원핫인코더로 변환한 내용을 새로운 데이터 프레임에 추가할때 컬럼명은 적당히 정해서 추가한다.
- Sex
- Embarked

##### Sex

In [10]:
from sklearn.preprocessing import OneHotEncoder

enc01 = OneHotEncoder()
titanic03 = titanic
enc01.fit(Sex.reshape(-1, 1))

NameError: name 'Sex' is not defined

##### Embarked

In [ ]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()
titanic04 = titanic