In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 무시 설정
import warnings
warnings.filterwarnings(action='ignore')

# 한글 깨짐 방지
plt.rcParams['font.family'] = 'Malgun Gothic'
# 마이너스 부호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

In [4]:
df0 = pd.read_csv('./spieces_data.csv')
df0.columns = df0.columns.str.strip()
df0

,대지위치,법정동코드,번,지,관리건축물대장PK,구조코드명,기타구조,주용도코드명,기타용동,지붕코드명,기타지붕
0,경상북도 포항시 남구 상도동 1-2번지,10100,1,2,122614933,철근콘크리트구조,철근콘크리트,공동주택,아파트,(철근)콘크리트,스라브
1,경상북도 포항시 남구 상도동 1-2번지,10100,1,2,122614934,철근콘크리트구조,철근콘크리트,공동주택,아파트,(철근)콘크리트,스라브
2,경상북도 포항시 남구 상도동 1-4번지,10100,1,4,122613341,벽돌구조,벽돌조,단독주택,"주택, 다세대주택",(철근)콘크리트,스라브
3,경상북도 포항시 남구 상도동 1-7번지,10100,1,7,122613342,벽돌구조,벽돌조,단독주택,주택,(철근)콘크리트,스라브
4,경상북도 포항시 남구 상도동 1-8번지,10100,1,8,122613343,벽돌구조,벽돌조,단독주택,다세대주택,(철근)콘크리트,스라브
...,...,...,...,...,...,...,...,...,...,...,...
45040,경상북도 포항시 남구 호미곶면 대동배리 416-3번지,35024,416,3,1226144835,일반목구조,목조,단독주택,NaN,기타지붕,함석
45041,경상북도 포항시 남구 호미곶면 대동배리 417-3번지,35024,417,3,12261100249842,경량철골구조,경량철골구조,단독주택,농가용주택,기타지붕,샌드위치판낼
45042,경상북도 포항시 남구 호미곶면 대동배리 419번지,35024,419,0,1226144836,경량철골구조,경량철골조(조립식),제2종근린생활시설,근린생활시설(일반음식점),기타지붕,75m/m판넬
45043,경상북도 포항시 남구 호미곶면 대동배리 419-1번지,35024,419,1,12261100251544,철근콘크리트구조,철근콘크리트구조,단독주택,단독주택,(철근)콘크리트,평슬라브
45044,경상북도 포항시 남구 호미곶면 대동배리 산42-7번지,35024,42,7,1226144839,일반목구조,목조,단독주택,주택,슬레이트,스레트

In [5]:
# 1. '대지위치' 컬럼 삭제
df00 = df0.drop(columns=['대지위치'])

# 2. 법정동코드 + 번 + 지 를 합쳐서 'code' 컬럼 생성
# 문자열 연산을 통해 하나로 합칩니다.
df00['code'] = df0['법정동코드'].astype(str) + '-' + \
                     df0['번'].astype(str) + '-' + \
                     df0['지'].astype(str)
    
# 3. 합치기에 사용된 기존 컬럼 삭제 (선택 사항)
df00= df00.drop(columns=['법정동코드', '번', '지'])

# 4. 필요한 컬럼만 선택
df00 = df00[['code', '주용도코드명']]
df00

              code     주용도코드명
0        10100-1-2       공동주택
1        10100-1-2       공동주택
2        10100-1-4       단독주택
3        10100-1-7       단독주택
4        10100-1-8       단독주택
...            ...        ...
45040  35024-416-3       단독주택
45041  35024-417-3       단독주택
45042  35024-419-0  제2종근린생활시설
45043  35024-419-1       단독주택
45044   35024-42-7       단독주택

[45045 rows x 2 columns]

In [6]:
df00.to_csv('species.csv', index=False, encoding='utf-8-sig')